### ISSUE TITLE
Could you plz narrate the whole process of executing sequence  here... Which files need to be executed after executing  train_adan?

### ISSUE THREAD

**Issue by SGT103** [Louisa-Luyi/adan#1]

**Comment by Louisa-Luyi** [comment]
After executing train_adan.py, you will obtain .h5 files storing the synthetic samples. Then, you can use them to train classifiers (like sample codes in svm_cls.py or dnn_cls.py).

**Comment by SGT103** [comment]
Yes, I did... an interesting project...I am trying to use other data augmentation techniques...thank you
